# File: F (Python 2.2)

import Localizer
UNLOCKED = 0
TALK_TO_TOM = 1
DEFEAT_FLUNKY_HQ = 2
TALK_TO_HQ = 3
WRONG_DOOR_HQ = 4
GO_TO_PLAYGROUND = 5
DEFEAT_FLUNKY_TOM = 6
TALK_TO_HQ_TOM = 7
SUIT_APPROACHING = 8
BUILDING_TAKEOVER = 9
reasonDict = {
    UNLOCKED: Localizer.FADoorCodes_UNLOCKED,
    TALK_TO_TOM: Localizer.FADoorCodes_TALK_TO_TOM,
    DEFEAT_FLUNKY_HQ: Localizer.FADoorCodes_DEFEAT_FLUNKY_HQ,
    TALK_TO_HQ: Localizer.FADoorCodes_TALK_TO_HQ,
    WRONG_DOOR_HQ: Localizer.FADoorCodes_WRONG_DOOR_HQ,
    GO_TO_PLAYGROUND: Localizer.FADoorCodes_GO_TO_PLAYGROUND,
    DEFEAT_FLUNKY_TOM: Localizer.FADoorCodes_DEFEAT_FLUNKY_TOM,
    TALK_TO_HQ_TOM: Localizer.FADoorCodes_TALK_TO_HQ_TOM,
    SUIT_APPROACHING: Localizer.FADoorCodes_SUIT_APPROACHING,
    BUILDING_TAKEOVER: Localizer.FADoorCodes_BUILDING_TAKEOVER }
