# File: F (Python 2.2)

from DirectNotifyGlobal import *
notify = directNotify.newCategory('FFI')
importModuleName = 'PandaModulesUnsqueezed'
generatedHeader = '# This file is automatically generated. It would be unwise to edit.\n\n'
CodeModuleNameList = []
InterrogateModuleName = None
wantComments = 1
wantTypeChecking = 1
